In [2]:
import pandas as pd
import io
from PIL import Image

In [3]:
all_documents=pd.read_csv('query_result_2022-02-03T11_48_29.164127Z.csv')

In [4]:
all_documents

case_id  \
0     1cd90041-b111-4063-b576-6d549c15d210   
1     1cd90041-b111-4063-b576-6d549c15d210   
2     1cd90041-b111-4063-b576-6d549c15d210   
3     1cd90041-b111-4063-b576-6d549c15d210   
4     1cd90041-b111-4063-b576-6d549c15d210   
...                                    ...   
4910  861ba1d1-2060-4ba0-9c84-12ed7b20269b   
4911  861ba1d1-2060-4ba0-9c84-12ed7b20269b   
4912  861ba1d1-2060-4ba0-9c84-12ed7b20269b   
4913  861ba1d1-2060-4ba0-9c84-12ed7b20269b   
4914  861ba1d1-2060-4ba0-9c84-12ed7b20269b   

                                              image_key          bucket  \
0     images_zippy/document_images/a5ea4c25-dc13-418...  rz-dre-weights   
1     images_zippy/document_images/a5ea4c25-dc13-418...  rz-dre-weights   
2     images_zippy/document_images/a5c86375-7bdd-4de...  rz-dre-weights   
3     images_zippy/document_images/a5b3d82f-0ba3-4df...  rz-dre-weights   
4     images_zippy/document_images/a5b3d82f-0ba3-4df...  rz-dre-weights   
...                                                 ...             ...   
4910  images_zippy/document_images/3c8878b5-22d4-434...  rz-dre-weights   
4911  images_zippy/document_images/3c768cea-79aa-44d...  rz-dre-weights   
4912  images_zippy/document_images/3c65bae5-fa74-407...  rz-dre-weights   
4913  images_zippy/document_images/3c65bae5-fa74-407...  rz-dre-weights   
4914  images_zippy/document_images/3c61cc13-279a-434...  rz-dre-weights   

      status       id  image_id  class     visibility     type  \
0     MERGED  5398148    817440    NaN      around_75  profile   
1     MERGED  5398147    817439    NaN      around_50  profile   
2     MERGED  5398146    817438    NaN  fully_visible  profile   
3     MERGED  5398145    817437    NaN      around_75  profile   
4     MERGED  5398141    817436    NaN  fully_visible  profile   
...      ...      ...       ...    ...            ...      ...   
4910  MERGED  5310605    822223    NaN      around_75  profile   
4911  MERGED  5310593    822222    NaN      around_75  profile   
4912  MERGED  5310582    822221    NaN  fully_visible  profile   
4913  MERGED  5310574    822220    NaN  fully_visible  profile   
4914  MERGED  5310570    822219    NaN  fully_visible  profile   

                                                   meta  parent_id  \
0     {"state": "Delhi", "documentSide": "Front", "d...        NaN   
1     {"state": "Delhi", "documentSide": "Front", "d...        NaN   
2     {"state": "Haryana", "documentSide": "Front", ...        NaN   
3     {"state": "Delhi", "documentSide": "Front", "d...        NaN   
4     {"state": "Delhi", "documentSide": "back", "do...        NaN   
...                                                 ...        ...   
4910  {"state": "Delhi", "documentSide": "Front", "d...        NaN   
4911  {"state": "Delhi", "documentSide": "Front", "d...        NaN   
4912  {"state": "Delhi", "documentSide": "Front", "d...        NaN   
4913  {"state": "Delhi", "documentSide": "Front", "d...        NaN   
4914  {"state": "Delhi", "documentSide": "Front", "d...        NaN   

      deleted_at                   created_at                   updated_at  \
0            NaN  2022-01-18T16:51:30.713466Z  2022-01-18T16:51:30.713466Z   
1            NaN  2022-01-18T16:49:21.053716Z  2022-01-18T16:49:21.053716Z   
2            NaN  2022-01-18T16:45:53.807403Z  2022-01-18T16:45:53.807403Z   
3            NaN  2022-01-18T16:43:07.688191Z  2022-01-18T16:43:07.688191Z   
4            NaN  2022-01-18T16:40:51.909386Z  2022-01-18T16:40:51.909386Z   
...          ...                          ...                          ...   
4910         NaN  2022-01-11T11:42:12.740376Z  2022-01-11T11:42:12.740376Z   
4911         NaN  2022-01-11T11:41:37.290455Z  2022-01-11T11:41:37.290455Z   
4912         NaN  2022-01-11T11:41:06.710899Z  2022-01-11T11:41:06.710899Z   
4913         NaN  2022-01-11T11:40:41.524001Z  2022-01-11T11:40:41.524001Z   
4914         NaN  2022-01-11T11:40:12.711692Z  2022-01-11T11:40:12.711692Z   

          

In [29]:
import requests
import json

def request_extractor(img_id_list):
    list_keys= []
    for img_id in img_id_list:
        list_keys.append({
                "key": img_id,
                "resourceId": img_id,
                "expiresIn": "86400"
            }
        )
    
    json_data = {
        "action": "get",
        "keys": list_keys,
        "bucket": "rz-dre-weights",
        "provider": "aws"
    }

    headers = {'Content-Type': 'application/json', 'rz-cuid': 'roadzen-via'}

    response = requests.post('https://baadal.roadzen.xyz/api/v1/files/signedurls',
                  data =json.dumps(json_data), headers=headers).json()
    return response

In [30]:
import time
import base64
def get_img_from_url(url):
    image_r = requests.get(url)
    image_b64 = base64.b64encode(image_r.content).decode('utf-8')
    fetch_status = image_r.status_code

    if fetch_status == 200:
        image = image_r.content
        total_sec = image_r.elapsed.total_seconds()
    else:
        image = None
        total_sec = image_r.elapsed.total_seconds()

    return image
#len(all_documents)
j = 0
while j < len(all_documents):
    print(len(all_documents))
    print('start j :', j )
    i = j
    while i < 100+j:
        print('---i---', i)
        img_list = all_documents["image_key"][i]
        dict1 = request_extractor(img_list)
        url = dict1['urls'][0]['signedUrl']
        img = get_img_from_url(url)
        image_name = "card_try/"+all_documents.iloc[i]["case_id"]+"_"+str(all_documents.iloc[i]["image_id"])+".jpg"
        im = Image.open(io.BytesIO(img))
        print('--image_name--', image_name)
        im.save(image_name)
        print('--url-- ', url)
        print('--img_list-- ',img_list)
        print('--case_id--',case_id)
        print('--image_id--',image_id)
        print('--dict1--',dict1)
        
        i+=1
    time.sleep(600)    
    j+=100
    print('---j---', j)

4915
start j : 0
---i--- 0


UnidentifiedImageError: cannot identify image file <_io.BytesIO object at 0x7fea8ed4eae0>

In [43]:
img_list = all_documents[2-1:2]["image_key"]
dict1 = request_extractor(img_list)
print(img_list)

1    images_zippy/document_images/a5ea4c25-dc13-418...
Name: image_key, dtype: object


In [44]:
print(dict1)

{'urls': [{'resourceId': 'images_zippy/document_images/a5ea4c25-dc13-4185-9c53-b799e70ee088_rc_image_back.jpg', 'key': 'images_zippy/document_images/a5ea4c25-dc13-4185-9c53-b799e70ee088_rc_image_back.jpg', 'signedUrl': 'https://rz-dre-weights.s3.amazonaws.com/images_zippy/document_images/a5ea4c25-dc13-4185-9c53-b799e70ee088_rc_image_back.jpg?X-Amz-Algorithm=AWS4-HMAC-SHA256&X-Amz-Credential=AKIA5ZLWJEWSRHIZI4N2%2F20220213%2Fus-east-1%2Fs3%2Faws4_request&X-Amz-Date=20220213T092550Z&X-Amz-Expires=86400&X-Amz-Signature=450f624f8b41ecde4d8f54abb9232fe60509e1cb547617b57853680638f59b7a&X-Amz-SignedHeaders=host', 'action': 'get'}]}


In [45]:
url = dict1['urls'][0]['signedUrl']
print(url)

https://rz-dre-weights.s3.amazonaws.com/images_zippy/document_images/a5ea4c25-dc13-4185-9c53-b799e70ee088_rc_image_back.jpg?X-Amz-Algorithm=AWS4-HMAC-SHA256&X-Amz-Credential=AKIA5ZLWJEWSRHIZI4N2%2F20220213%2Fus-east-1%2Fs3%2Faws4_request&X-Amz-Date=20220213T092550Z&X-Amz-Expires=86400&X-Amz-Signature=450f624f8b41ecde4d8f54abb9232fe60509e1cb547617b57853680638f59b7a&X-Amz-SignedHeaders=host


In [46]:
import base64
def get_img_from_url(url):
    image_r = requests.get(url)
    image_b64 = base64.b64encode(image_r.content).decode('utf-8')
    fetch_status = image_r.status_code

    if fetch_status == 200:
        image = image_r.content
        total_sec = image_r.elapsed.total_seconds()
    else:
        image = None
        total_sec = image_r.elapsed.total_seconds()

    return image

img = get_img_from_url(url)
print(img)

b'\xff\xd8\xff\xe0\x00\x10JFIF\x00\x01\x01\x00\x00\x01\x00\x01\x00\x00\xff\xdb\x00C\x00\x02\x01\x01\x01\x01\x01\x02\x01\x01\x01\x02\x02\x02\x02\x02\x04\x03\x02\x02\x02\x02\x05\x04\x04\x03\x04\x06\x05\x06\x06\x06\x05\x06\x06\x06\x07\t\x08\x06\x07\t\x07\x06\x06\x08\x0b\x08\t\n\n\n\n\n\x06\x08\x0b\x0c\x0b\n\x0c\t\n\n\n\xff\xdb\x00C\x01\x02\x02\x02\x02\x02\x02\x05\x03\x03\x05\n\x07\x06\x07\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\xff\xc0\x00\x11\x08\x048\x07\x80\x03\x01"\x00\x02\x11\x01\x03\x11\x01\xff\xc4\x00\x1f\x00\x00\x01\x05\x01\x01\x01\x01\x01\x01\x00\x00\x00\x00\x00\x00\x00\x00\x01\x02\x03\x04\x05\x06\x07\x08\t\n\x0b\xff\xc4\x00\xb5\x10\x00\x02\x01\x03\x03\x02\x04\x03\x05\x05\x04\x04\x00\x00\x01}\x01\x02\x03\x00\x04\x11\x05\x12!1A\x06\x13Qa\x07"q\x142\x81\x91\xa1\x08#B\xb1\xc1\x15R\xd1\xf0$3br\x82\t\n\x16\x17\x18\x19\x1a%&\'()*456789:CDEFGHIJSTUVWXYZcdefghijstuvwxyz\x83\x84\x85\x86\x87\x88\x89\x8a\x92\x93\x94\x95\x96\x97\x98

In [47]:

im = Image.open(io.BytesIO(img))
#im = io.BytesIO(img)
im.save("geeks.jpg")


In [ ]:
img_byte_arr = io.BytesIO()
img.save(img_byte_arr, format='PNG')
img_byte_arr = img_byte_arr.getvalue()

In [52]:
all_documents["meta"].iloc[4544]

'{"state": "Bihar", "documentSide": "Front", "documentType": "RC", "vehicleColor": "", "vehiclesCount": "", "documentRcType": "DigiLocker"}'

In [ ]:
Authorization: AWS4-HMAC-SHA256 Credential=AKIDEXAMPLE/20150830/us-east-1/iam/aws4_request, SignedHeaders=content-type;host;x-amz-date, Signature=5d672d79c15b13162d9279b0855cfba6789a8edb4c82c400e06b5924a6f2b5d7

In [6]:
all_documents.iloc[2690]["case_id"]+"_"+str(all_documents.iloc[2690]["image_id"])+".jpg"

'6309b3a9-8f9c-4f20-b9ea-9b2214665a8a_820152.jpg'

In [35]:
all_documents.iloc[0]["polygon"]

'[{"x": 294.9794238683128, "y": 208.06584362139918}, {"x": 313.4156378600823, "y": 186.99588477366254}, {"x": 352.9218106995885, "y": 181.72839506172843}, {"x": 1416.954732510288, "y": 163.29218106995884}, {"x": 1461.7283950617284, "y": 176.46090534979425}, {"x": 1466.9958847736623, "y": 210.69958847736623}, {"x": 1503.8683127572017, "y": 513.5802469135803}, {"x": 1566.275288080743, "y": 869.7231981357816}, {"x": 1551.275720164609, "y": 906.0082304526749}, {"x": 1538.1069958847736, "y": 914.8592151569061}, {"x": 611.0288065843621, "y": 945.5144032921811}, {"x": 271.275720164609, "y": 958.6831275720165}, {"x": 237.03703703703704, "y": 950.7818930041152}, {"x": 215.96707818930042, "y": 916.5432098765432}, {"x": 247.57201646090536, "y": 650.5349794238683}, {"x": 289.7119341563786, "y": 231.7695473251029}]'

In [39]:
img_list = list(all_documents[500:8900]["type"])
print(img_list)

['profile', 'profile', 'profile', 'profile', 'profile', 'profile', 'profile', 'profile', 'profile', 'profile', 'profile', 'profile', 'profile', 'profile', 'profile', 'profile', 'profile', 'profile', 'profile', 'profile', 'profile', 'profile', 'profile', 'profile', 'profile', 'profile', 'profile', 'profile', 'profile', 'profile', 'profile', 'profile', 'profile', 'profile', 'profile', 'profile', 'profile', 'profile', 'profile', 'profile', 'profile', 'profile', 'profile', 'profile', 'profile', 'profile', 'profile', 'profile', 'profile', 'profile', 'profile', 'profile', 'profile', 'profile', 'profile', 'profile', 'profile', 'profile', 'profile', 'profile', 'profile', 'profile', 'profile', 'profile', 'profile', 'profile', 'profile', 'profile', 'profile', 'profile', 'profile', 'profile', 'profile', 'profile', 'profile', 'profile', 'profile', 'profile', 'profile', 'profile', 'profile', 'profile', 'profile', 'profile', 'profile', 'profile', 'profile', 'profile', 'profile', 'profile', 'profile'

In [54]:
all_documents=pd.read_csv('query_result_2022-02-03T11_48_29.164127Z.csv')

In [55]:
all_documents

case_id  \
0     1cd90041-b111-4063-b576-6d549c15d210   
1     1cd90041-b111-4063-b576-6d549c15d210   
2     1cd90041-b111-4063-b576-6d549c15d210   
3     1cd90041-b111-4063-b576-6d549c15d210   
4     1cd90041-b111-4063-b576-6d549c15d210   
...                                    ...   
4910  861ba1d1-2060-4ba0-9c84-12ed7b20269b   
4911  861ba1d1-2060-4ba0-9c84-12ed7b20269b   
4912  861ba1d1-2060-4ba0-9c84-12ed7b20269b   
4913  861ba1d1-2060-4ba0-9c84-12ed7b20269b   
4914  861ba1d1-2060-4ba0-9c84-12ed7b20269b   

                                              image_key          bucket  \
0     images_zippy/document_images/a5ea4c25-dc13-418...  rz-dre-weights   
1     images_zippy/document_images/a5ea4c25-dc13-418...  rz-dre-weights   
2     images_zippy/document_images/a5c86375-7bdd-4de...  rz-dre-weights   
3     images_zippy/document_images/a5b3d82f-0ba3-4df...  rz-dre-weights   
4     images_zippy/document_images/a5b3d82f-0ba3-4df...  rz-dre-weights   
...                                                 ...             ...   
4910  images_zippy/document_images/3c8878b5-22d4-434...  rz-dre-weights   
4911  images_zippy/document_images/3c768cea-79aa-44d...  rz-dre-weights   
4912  images_zippy/document_images/3c65bae5-fa74-407...  rz-dre-weights   
4913  images_zippy/document_images/3c65bae5-fa74-407...  rz-dre-weights   
4914  images_zippy/document_images/3c61cc13-279a-434...  rz-dre-weights   

      status       id  image_id  class     visibility     type  \
0     MERGED  5398148    817440    NaN      around_75  profile   
1     MERGED  5398147    817439    NaN      around_50  profile   
2     MERGED  5398146    817438    NaN  fully_visible  profile   
3     MERGED  5398145    817437    NaN      around_75  profile   
4     MERGED  5398141    817436    NaN  fully_visible  profile   
...      ...      ...       ...    ...            ...      ...   
4910  MERGED  5310605    822223    NaN      around_75  profile   
4911  MERGED  5310593    822222    NaN      around_75  profile   
4912  MERGED  5310582    822221    NaN  fully_visible  profile   
4913  MERGED  5310574    822220    NaN  fully_visible  profile   
4914  MERGED  5310570    822219    NaN  fully_visible  profile   

                                                   meta  parent_id  \
0     {"state": "Delhi", "documentSide": "Front", "d...        NaN   
1     {"state": "Delhi", "documentSide": "Front", "d...        NaN   
2     {"state": "Haryana", "documentSide": "Front", ...        NaN   
3     {"state": "Delhi", "documentSide": "Front", "d...        NaN   
4     {"state": "Delhi", "documentSide": "back", "do...        NaN   
...                                                 ...        ...   
4910  {"state": "Delhi", "documentSide": "Front", "d...        NaN   
4911  {"state": "Delhi", "documentSide": "Front", "d...        NaN   
4912  {"state": "Delhi", "documentSide": "Front", "d...        NaN   
4913  {"state": "Delhi", "documentSide": "Front", "d...        NaN   
4914  {"state": "Delhi", "documentSide": "Front", "d...        NaN   

      deleted_at                   created_at                   updated_at  \
0            NaN  2022-01-18T16:51:30.713466Z  2022-01-18T16:51:30.713466Z   
1            NaN  2022-01-18T16:49:21.053716Z  2022-01-18T16:49:21.053716Z   
2            NaN  2022-01-18T16:45:53.807403Z  2022-01-18T16:45:53.807403Z   
3            NaN  2022-01-18T16:43:07.688191Z  2022-01-18T16:43:07.688191Z   
4            NaN  2022-01-18T16:40:51.909386Z  2022-01-18T16:40:51.909386Z   
...          ...                          ...                          ...   
4910         NaN  2022-01-11T11:42:12.740376Z  2022-01-11T11:42:12.740376Z   
4911         NaN  2022-01-11T11:41:37.290455Z  2022-01-11T11:41:37.290455Z   
4912         NaN  2022-01-11T11:41:06.710899Z  2022-01-11T11:41:06.710899Z   
4913         NaN  2022-01-11T11:40:41.524001Z  2022-01-11T11:40:41.524001Z   
4914         NaN  2022-01-11T11:40:12.711692Z  2022-01-11T11:40:12.711692Z   

          

In [56]:
case_id = all_documents["case_id"]
image_id = all_documents["image_id"]

visibility = all_documents["visibility"]
meta = all_documents["meta"]
polygon = all_documents["polygon"]
id1 = all_documents["id"]
#image_name = all_documents["image_name"]

In [57]:
df = pd.DataFrame(columns=['case_id','image_id','image_name', 'visibility','meta', 'polygon', 'id'])

In [58]:
for i in range(len(image_id)):
    image_name = all_documents.iloc[i]["case_id"]+"_"+str(all_documents.iloc[i]["image_id"])+".jpg"
    df = df.append({'case_id': case_id[i] ,'image_id' : image_id[i],'image_name' : image_name,'visibility' : visibility[i] ,'meta' : meta[i] ,'polygon' : polygon[i] ,'id' : id1[i] },ignore_index=True)

df

case_id image_id  \
0     1cd90041-b111-4063-b576-6d549c15d210   817440   
1     1cd90041-b111-4063-b576-6d549c15d210   817439   
2     1cd90041-b111-4063-b576-6d549c15d210   817438   
3     1cd90041-b111-4063-b576-6d549c15d210   817437   
4     1cd90041-b111-4063-b576-6d549c15d210   817436   
...                                    ...      ...   
4910  861ba1d1-2060-4ba0-9c84-12ed7b20269b   822223   
4911  861ba1d1-2060-4ba0-9c84-12ed7b20269b   822222   
4912  861ba1d1-2060-4ba0-9c84-12ed7b20269b   822221   
4913  861ba1d1-2060-4ba0-9c84-12ed7b20269b   822220   
4914  861ba1d1-2060-4ba0-9c84-12ed7b20269b   822219   

                                           image_name     visibility  \
0     1cd90041-b111-4063-b576-6d549c15d210_817440.jpg      around_75   
1     1cd90041-b111-4063-b576-6d549c15d210_817439.jpg      around_50   
2     1cd90041-b111-4063-b576-6d549c15d210_817438.jpg  fully_visible   
3     1cd90041-b111-4063-b576-6d549c15d210_817437.jpg      around_75   
4     1cd90041-b111-4063-b576-6d549c15d210_817436.jpg  fully_visible   
...                                               ...            ...   
4910  861ba1d1-2060-4ba0-9c84-12ed7b20269b_822223.jpg      around_75   
4911  861ba1d1-2060-4ba0-9c84-12ed7b20269b_822222.jpg      around_75   
4912  861ba1d1-2060-4ba0-9c84-12ed7b20269b_822221.jpg  fully_visible   
4913  861ba1d1-2060-4ba0-9c84-12ed7b20269b_822220.jpg  fully_visible   
4914  861ba1d1-2060-4ba0-9c84-12ed7b20269b_822219.jpg  fully_visible   

                                                   meta  \
0     {"state": "Delhi", "documentSide": "Front", "d...   
1     {"state": "Delhi", "documentSide": "Front", "d...   
2     {"state": "Haryana", "documentSide": "Front", ...   
3     {"state": "Delhi", "documentSide": "Front", "d...   
4     {"state": "Delhi", "documentSide": "back", "do...   
...                                                 ...   
4910  {"state": "Delhi", "documentSide": "Front", "d...   
4911  {"state": "Delhi", "documentSide": "Front", "d...   
4912  {"state": "Delhi", "documentSide": "Front", "d...   
4913  {"state": "Delhi", "documentSide": "Front", "d...   
4914  {"state": "Delhi", "documentSide": "Front", "d...   

                                                polygon       id  
0     [{"x": 294.9794238683128, "y": 208.06584362139...  5398148  
1     [{"x": 287.0781893004115, "y": 165.92592592592...  5398147  
2     [{"x": 229.908592321755, "y": 203.583180987202...  5398146  
3     [{"x": 551.0786106032906, "y": 328.19012797074...  5398145  
4     [{"x": 542.3034734917733, "y": 257.98903107861...  5398141  
...                                                 ...      ...  
4910  [{"x": 406.7163288040666, "y": 281.14789748033...  5310605  
4911  [{"x": 454.39844800936464, "y": 303.3995531094...  5310593  
4912  [{"x": 416.25275264512624, "y": 193.7306789372...  5310582  
4913  [{"x": 293.86864668486135, "y": 157.1743875465...  5310574  
4914  [{"x": 320.8885142345302, "y": 247.77041403663...  5310570  

[4915 rows x 7 columns]

In [11]:
df.to_csv('card_data.csv')

NameError: name 'df' is not defined

In [185]:
data=pd.read_csv('card_data.csv')
print(len(data))
poly_line = data["polygon"][2860]
image_name = data["image_name"][2860]
print(poly_line)
print(image_name)

4915
[{"x": 234.20097440831802, "y": 201.72548540900738}, {"x": 238.4362685259651, "y": 179.13725011488972}, {"x": 262.4362685259651, "y": 156.54901482077207}, {"x": 1418.6715626436123, "y": 156.54901482077207}, {"x": 1439.8480332318475, "y": 162.1960736443015}, {"x": 1456.7892097024358, "y": 187.60783835018384}, {"x": 1444.0833273494945, "y": 882.5098087086398}, {"x": 1442.6715626436123, "y": 900.8627498851104}, {"x": 1417.25979793773, "y": 927.6862792968751}, {"x": 276.5539155847886, "y": 912.1568675321691}, {"x": 256.7892097024357, "y": 896.6274557674633}, {"x": 239.84803323184744, "y": 872.6274557674633}]
008e6476-ec4d-428a-ab68-69b022286d08_820296.jpg


In [178]:
res = json.loads(poly_line)
print(res)
res1 = len(res)
print(res1)
coordinates = []
for i in range(len(res)):
    a = res[i]['x']
    b = res[i]['y']
    c = [int(a) , int(b)]
    coordinates.append(c)
    coordinates.append(c)
    
print(coordinates)

[{'x': 234.20097440831802, 'y': 201.72548540900738}, {'x': 238.4362685259651, 'y': 179.13725011488972}, {'x': 262.4362685259651, 'y': 156.54901482077207}, {'x': 1418.6715626436123, 'y': 156.54901482077207}, {'x': 1439.8480332318475, 'y': 162.1960736443015}, {'x': 1456.7892097024358, 'y': 187.60783835018384}, {'x': 1444.0833273494945, 'y': 882.5098087086398}, {'x': 1442.6715626436123, 'y': 900.8627498851104}, {'x': 1417.25979793773, 'y': 927.6862792968751}, {'x': 276.5539155847886, 'y': 912.1568675321691}, {'x': 256.7892097024357, 'y': 896.6274557674633}, {'x': 239.84803323184744, 'y': 872.6274557674633}]
12
[[234, 201], [234, 201], [238, 179], [238, 179], [262, 156], [262, 156], [1418, 156], [1418, 156], [1439, 162], [1439, 162], [1456, 187], [1456, 187], [1444, 882], [1444, 882], [1442, 900], [1442, 900], [1417, 927], [1417, 927], [276, 912], [276, 912], [256, 896], [256, 896], [239, 872], [239, 872]]


In [179]:
pts = np.array(coordinates)
print(pts)

[[ 234  201]
 [ 234  201]
 [ 238  179]
 [ 238  179]
 [ 262  156]
 [ 262  156]
 [1418  156]
 [1418  156]
 [1439  162]
 [1439  162]
 [1456  187]
 [1456  187]
 [1444  882]
 [1444  882]
 [1442  900]
 [1442  900]
 [1417  927]
 [1417  927]
 [ 276  912]
 [ 276  912]
 [ 256  896]
 [ 256  896]
 [ 239  872]
 [ 239  872]]


In [160]:
image_path = 'card_images/'+image_name
image = cv2.imread(image_path)
#print(image)

[[[  0   2  29]
  [  0   2  29]
  [  0   1  28]
  ...
  [  0   0   9]
  [  0   1  10]
  [  0   1  10]]

 [[ 95 109 138]
  [ 94 108 137]
  [ 92 106 135]
  ...
  [ 24  31  40]
  [ 29  34  43]
  [ 28  35  44]]

 [[ 87 109 144]
  [ 86 108 143]
  [ 84 106 141]
  ...
  [ 21  30  39]
  [ 25  32  41]
  [ 25  34  43]]

 ...

 [[ 22  43  41]
  [ 22  43  41]
  [ 22  42  43]
  ...
  [  0   0   0]
  [  0   0   0]
  [  0   0   0]]

 [[ 21  42  40]
  [ 20  41  39]
  [ 20  40  41]
  ...
  [  0   0   0]
  [  0   0   0]
  [  0   0   0]]

 [[ 20  41  39]
  [ 19  40  38]
  [ 17  37  38]
  ...
  [  0   0   0]
  [  0   0   0]
  [  0   0   0]]]


In [161]:
pts = pts.reshape((-1, 1, 2))
  
isClosed = True

In [162]:
color = (255, 0, 0)
  
# Line thickness of 2 px
thickness = 2
  
# Using cv2.polylines() method
# Draw a Blue polygon with 
# thickness of 1 px
image = cv2.polylines(image, [pts], 
                      isClosed, color, thickness)
#print(image)  

In [163]:
filename = 'output_polyline/output_'+image_name
cv2.imwrite(filename, image)

True

In [5]:
poly_line = data["visibility"] 
# Creating an empty dictionary
for i in range(len(data))
freq = {}
for item in my_list:
    if (item in freq):
        freq[item] += 1
    else:
        freq[item] = 1

for key, value in freq.items():
    print ("% d : % d"%(key, value))

SyntaxError: invalid syntax (2692096539.py, line 3)

In [33]:
meta = all_documents["meta"]
visibility_list = []
for i in range(len(visibility)):
    meta = all_documents["meta"][i]
    res = json.loads(meta)
    res = res['state']
    visibility_list.append(res)
print(visibility_list)        

['Delhi', 'Delhi', 'Haryana', 'Delhi', 'Delhi', 'Delhi', 'Haryana', 'Delhi', 'Delhi', 'Delhi', 'Delhi', 'Karnataka', 'Haryana', 'Bihar', 'Delhi', 'Delhi', 'Delhi', 'Delhi', 'Haryana', 'Haryana', 'Delhi', 'Haryana', 'West_Bengal', 'Delhi', 'Delhi', 'Rajasthan', 'Delhi', 'Delhi', 'Haryana', 'Haryana', 'Haryana', 'Delhi', 'Delhi', 'Rajasthan', 'Delhi', 'Haryana', 'Delhi', 'Rajasthan', 'Delhi', 'Haryana', 'Haryana', 'Delhi', 'Delhi', 'Delhi', 'Delhi', 'Haryana', 'Delhi', 'Delhi', 'Haryana', 'Haryana', 'Uttar_Pradesh', 'Delhi', 'Delhi', 'Delhi', 'Delhi', 'Delhi', 'Rajasthan', 'Delhi', 'Delhi', 'Uttarakhand', 'Uttarakhand', 'Delhi', 'Delhi', 'Delhi', 'Delhi', 'Delhi', 'Delhi', 'Delhi', 'Delhi', 'Delhi', 'Delhi', 'Uttar_Pradesh', 'Delhi', 'Delhi', 'Haryana', 'Delhi', 'Delhi', 'Delhi', 'Delhi', 'Haryana', 'Delhi', 'Delhi', 'Delhi', 'Haryana', 'Haryana', 'Delhi', 'Delhi', 'Delhi', 'Haryana', 'Delhi', 'Haryana', 'Haryana', 'Delhi', 'Delhi', 'Delhi', 'Delhi', 'Delhi', 'Delhi', 'Delhi', 'Delhi', '

In [36]:
meta = all_documents["meta"][10]
#res = json.loads(meta)
#res = res['state']

#print(res)
print(meta)

{"state": "Delhi", "documentSide": "Front", "documentType": "RC", "vehicleColor": "", "vehiclesCount": "", "documentRcType": "Card"}


In [34]:
def CountFrequency(my_list):
 
    # Creating an empty dictionary
    freq = {}
    for item in my_list:
        if (item in freq):
            freq[item] += 1
        else:
            freq[item] = 1
    print(freq)

In [35]:
#print(visibility_list)
CountFrequency(visibility_list)

{'Delhi': 3683, 'Haryana': 473, 'Karnataka': 3, 'Bihar': 131, 'West_Bengal': 14, 'Rajasthan': 138, 'Uttar_Pradesh': 340, 'Uttarakhand': 37, 'Puducherry': 4, 'Chandigarh': 11, 'Chhattisgarh': 6, 'Odisha': 8, 'Jharkhand': 12, 'Assam': 7, 'Gujarat': 1, 'Himachal_Pradesh': 12, 'Meghalaya': 1, 'Punjab': 12, 'Maharashtra': 10, 'Kerala': 3, 'Telangana': 1, 'Nagaland': 6, 'Madhya_Pradesh': 1, 'Tamil_Nadu': 1}


In [176]:
def get_polygons(marking,width,height):
    try:
        polygon = marking['boundingBox']['polygons'][0]
        if len(polygon)==0: return None,None,None,None,None

        polygon_allx = [int(np.floor(p['x'])) for p in polygon]
        polygon_ally = [int(np.floor(p['y'])) for p in polygon]

        min_x = int(np.min(polygon_allx))
        min_y = int(np.min(polygon_ally))
        max_x = int(np.max(polygon_allx))
        max_y = int(np.max(polygon_ally))


        if (max_x>width) or (max_y>height):
            diffx = max_x-width
            diffy = max_y-height
            if 0<diffx<=10:
                max_x = width
            elif 0<diffy<=10:
                max_y = height
            else:
                print('issue in-',max_x,max_y,width,height)
                return None,None,None,None,None

        poly = [(x + 0.5, y + 0.5) for x, y in zip(polygon_allx, polygon_ally)]
        poly = list(itertools.chain.from_iterable(poly))

        return min_x,min_y,max_x,max_y,poly
    except:
        return None,None,None,None,None

In [187]:
im = cv2.imread('card_images/008e6476-ec4d-428a-ab68-69b022286d08_820296.jpg')
height, width, c = im.shape
print(im.shape)
poly_line = data["polygon"][2860]
get_polygons(poly_line,width,height)

(1080, 1920, 3)


(None, None, None, None, None)

In [190]:
def bounding_box(points):
    x_coordinates, y_coordinates = zip(*points)

    return [(min(x_coordinates), min(y_coordinates)), (max(x_coordinates), max(y_coordinates))]

In [198]:

print(topleft)

(234, 156)


In [199]:
import cv2
img = cv2.imread('card_images/008e6476-ec4d-428a-ab68-69b022286d08_820296.jpg')
#775;432;811;468
#cv2.rectangle(img, (Roi_X1[i], Roi_Y1[i]), (Roi_X2[i], Roi_Y2[i]), (0, 255, 0), 1)
topleft, bottomright = bounding_box(pts)
cv2.rectangle(img, topleft, bottomright, (255, 0, 0), 4)
#head_tail = os.path.split(image_list[i])
#filename = head_tail[1]
#print("filename :", filename)
#file_path = os.path.join(CWD_PATH, 'gtsdb_data','bbox','test',filename)
cv2.imwrite('bbox.jpg', img)

True